[workspace]
resolver = "2"
members = ["contracts", "contracts/wallet", "server"]

[workspace.dependencies]
# sdk = { package = "hyle-contract-sdk", version = "0.13.0-rc.4" }
# client-sdk = { default-features = false, package = "hyle-client-sdk", version = "0.13.0-rc.4" }
# hyle = { version = "0.13.0-rc.4" }

sdk = { git = "https://github.com/Hyle-org/hyle.git", package = "hyle-contract-sdk", branch = "refacto/multiproof" }
client-sdk = { git = "https://github.com/Hyle-org/hyle.git", default-features = false, package = "hyle-client-sdk", branch = "refacto/multiproof" }
hyle = { git = "https://github.com/Hyle-org/hyle.git", branch = "refacto/multiproof" }
hyle-hyllar = { git = "https://github.com/Hyle-org/hyle.git", package = "hyle-hyllar", branch = "refacto/multiproof" }

contracts = { path = "contracts", default-features = false, package = "contracts" }
wallet = { path = "contracts/wallet", package = "wallet" }

[workspace.package]
version = "0.4.1"
edition = "2021"

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
