id = "hyle-scaffold-app"
log_format = "full"
contract_name = "wallet"
rest_server_port = 4000
da_read_from = "127.0.0.1:4141"
rest_server_max_body_size = 10_485_760
data_directory = "data"

[websocket]
port = 8081
ws_path = "/ws"
health_path = "/ws_health"
peer_check_interval = 100
